# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 14:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import su.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('su', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('cg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Coordinator UUID')),
                ('cg_name', models.CharField(max_length=32, verbose_name='Coordinator Name')),
                ('cg_bitsid', models.CharField(max_length=32, unique=True, verbose_name='Coordinator Bits ID')),
                ('assoc_name', models.CharField(max_length=64, verbose_name='Association')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reg_by', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateMailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('mails', models.IntegerField(default=0, verbose_name='Mails Sent')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('gm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Event UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Event Name')),
                ('meal', models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows'), ('Bottom', 'Bottom')], default='Workshop', max_length=16, verbose_name='Event Type')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Registration Date')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('deadline2', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=128)),
                ('excel', models.FileField(upload_to=su.models.content_album_name)),
                ('mails', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('price', models.IntegerField(default=0, verbose_name='Event Price')),
                ('image', models.ImageField(upload_to=su.models.content_album_name, verbose_name='Event image')),
                ('venue', models.CharField(max_length=16, verbose_name='Event Venue')),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su.Coord', verbose_name='Coordinator Id')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Student Id')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='Bits Email Id')),
                ('mail', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('meal', models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows')], default='Workshop', max_length=16, verbose_name='Size Selected')),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out')], max_length=128)),
                ('room', models.CharField(default='4126', max_length=32, verbose_name='Room No.')),
                ('bhawan', models.CharField(default='BD', max_length=32, verbose_name='Bhawan')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='su.Event', verbose_name='Event Id')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Stud Id')),
                ('name', models.CharField(max_length=32)),
                ('bits_id', models.CharField(max_length=32, unique=True, verbose_name='BITS ID')),
                ('bhawan', models.CharField(max_length=32)),
                ('room_no', models.CharField(max_length=4, verbose_name='Room No.')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='Bits Email Id')),
            ],
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('gm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wear UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Wear Name')),
                ('meal', models.CharField(choices=[('T Shirt', 'T Shirt'), ('Sweat Shirt', 'Sweat Shirt')], default='T Shirt', max_length=16, verbose_name='Wear Type')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Final Submission Date')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('deadline2', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=128)),
                ('excel', models.FileField(upload_to=su.models.content_album_name)),
                ('mails', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('price', models.IntegerField(default=0, verbose_name='Wear Price')),
                ('image', models.ImageField(upload_to=su.models.content_album_name, verbose_name='Wear image')),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su.Coord', verbose_name='Coordinator Id')),
            ],
        ),
        migrations.CreateModel(
            name='Wear_Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Student Id')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='Bits Email Id')),
                ('mail', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('meal', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=16, verbose_name='Size Selected')),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out')], max_length=128)),
                ('room', models.CharField(default='4126', max_length=32, verbose_name='Room No.')),
                ('bhawan', models.CharField(default='BD', max_length=32, verbose_name='Bhawan')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='su.Wear', verbose_name='Wear Id')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wear_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
        migrations.AlterUniqueTogether(
            name='event_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
    ]
