# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0002_auto_20190201_2002'),
    ]

    operations = [
    ]
