# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0003_auto_20190201_2003'),
    ]

    operations = [
    ]
