# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0005_auto_20190201_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bits_id',
            field=models.CharField(max_length=64, verbose_name='BITS ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Bits EStudentmail Id'),
        ),
    ]
