# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0006_auto_20190201_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bits_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='BITS ID'),
        ),
    ]
