# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0009_auto_20190201_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='cg_bitsid',
            field=models.CharField(max_length=32, unique=True, verbose_name="Coordinator Bits ID (without a 'P')"),
        ),
    ]
