# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0010_auto_20190201_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meal',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows'), ('Other', 'Other')], default='Workshop', max_length=16, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='meal',
            field=models.CharField(choices=[('T Shirt', 'T Shirt'), ('Sweat Shirt', 'Sweat Shirt'), ('Other', 'Other')], default='T Shirt', max_length=16, verbose_name='Wear Type'),
        ),
    ]
