# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0013_auto_20190201_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Event Price'),
        ),
        migrations.AddField(
            model_name='wear',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Wear Price'),
        ),
    ]
