# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-01 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import su.models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0014_auto_20190201_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='excel',
            field=models.FileField(blank=True, upload_to=su.models.content_album_name),
        ),
        migrations.AlterField(
            model_name='wear',
            name='excel',
            field=models.FileField(blank=True, upload_to=su.models.content_album_name),
        ),
    ]
