# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0015_auto_20190202_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_student',
            name='meal',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Prof Shows', 'Prof Shows')], default='Workshop', max_length=16, verbose_name='Event Selected'),
        ),
    ]
